"""Small, reusable PowerPoint builder for the initial project foundation."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt


DEFAULT_FONT = "Microsoft YaHei"


def _set_text_style(paragraph, *, size: int, bold: bool = False) -> None:
    paragraph.alignment = PP_ALIGN.LEFT
    for run in paragraph.runs:
        run.font.name = DEFAULT_FONT
        run.font.size = Pt(size)
        run.font.bold = bold


def build_presentation(
    title: str,
    subtitle: str,
    bullets: Iterable[str],
    output_path: str | Path,
    *,
    overwrite: bool = False,
) -> Path:
    """Build a simple editable 16:9 presentation and return its output path."""
    destination = Path(output_path).expanduser().resolve()
    if destination.suffix.lower() != ".pptx":
        raise ValueError("输出文件必须使用 .pptx 扩展名")
    if destination.exists() and not overwrite:
        raise FileExistsError(f"目标文件已经存在：{destination}")

    normalized_title = title.strip()
    if not normalized_title:
        raise ValueError("标题不能为空")
    normalized_bullets = [item.strip() for item in bullets if item.strip()]

    presentation = Presentation()
    presentation.slide_width = Inches(13.333)
    presentation.slide_height = Inches(7.5)
    presentation.core_properties.title = normalized_title
    presentation.core_properties.subject = "Generated by KY PPT Generator"

    title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
    title_slide.shapes.title.text = normalized_title
    subtitle_shape = title_slide.placeholders[1]
    subtitle_shape.text = subtitle.strip()
    _set_text_style(title_slide.shapes.title.text_frame.paragraphs[0], size=30, bold=True)
    _set_text_style(subtitle_shape.text_frame.paragraphs[0], size=18)

    if normalized_bullets:
        content_slide = presentation.slides.add_slide(presentation.slide_layouts[1])
        content_slide.shapes.title.text = "核心内容"
        _set_text_style(content_slide.shapes.title.text_frame.paragraphs[0], size=26, bold=True)

        text_frame = content_slide.placeholders[1].text_frame
        text_frame.clear()
        for index, item in enumerate(normalized_bullets):
            paragraph = text_frame.paragraphs[0] if index == 0 else text_frame.add_paragraph()
            paragraph.text = item
            paragraph.level = 0
            paragraph.space_after = Pt(10)
            _set_text_style(paragraph, size=20)

    destination.parent.mkdir(parents=True, exist_ok=True)
    presentation.save(destination)
    return destination
